### ISSUE TITLE
roadmap

### ISSUE THREAD

**Issue by bsr203** [dropbox/scooter#8]
Hi,

Thanks for open sourcing this library and your effort on this. Can you provide some details on future plans or roadmap. I like it being lean, at the same time wonder about adding new components like Navbar, dropdowns, etc. Will it depend on dropbox's requirement or will be driven by the community?

Thanks
bsr

**Comment by daneden** [comment]
Hey @bsr203!

Since Scooter is first and foremost a Dropbox-oriented project, its progress/roadmap will most likely be driven by product needs.

We’re also currently focusing primarily on implementing the framework site-wide before moving our efforts to evolving the framework itself. In other words, a roadmap is a way off yet, but when we set our eyes on the future, that planning will happen as much in the open as possible :smile:

**Comment by bsr203** [comment]
thanks @daneden
